apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environments-appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/therealdavidbour/Initech-config.git
        revision: HEAD
        branches:
          - pattern: "^env/.*"
  template:
    metadata:
      name: 'root-{{ .branch | replace "/" "-" }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/therealdavidbour/Initech-config.git
        targetRevision: '{{ .branch }}'
        path: apps-rendered
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
