---
# Source: apps/templates/recipe-api.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recipe-api-vnv
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/initech-ai/Initech-config.git
    targetRevision: env/vnv
    path: services/recipe-api/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: vnv
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
